name: streaming_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5

  # UI & Animations
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0 # Added for indicators

  # Utils
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
